---
driver:
    name: vagrant

provisioner:
  name: puppet_apply
  manifests_path:  manifests
  modules_path: modules-mycompany
  hiera_data_path: hieradata
  require_puppet_omnibus: false
  puppet_omnibus_url: bad_url
  puppet_debug: true
  puppet_verbose: true
  custom_facts:
    role_name1: webserver

platforms:
  - name: nocm_ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      box: nocm_ubuntu-12.04
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
  - name: nocm_centos-6.5
    driver_plugin: vagrant
    driver_config:
      box: nocm_centos-6.5
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
  - name: centos-6.4
    driver:  vagrant

suites:
  - name: default