Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  # no synched folders 
  config.vm.synced_folder "/", "/vagrant", disabled: true

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "<insert key>"
    aws.secret_access_key = "<insert secret key>"
    aws.region = "us-east-1"
    aws.availability_zone = "us-east-1c"
    aws.keypair_name = "<insert key pair name>"

    aws.ami = "ami-d0f89fb9"
    aws.security_groups = "default"
    aws.tags = { 'Name' => 'default'}
    aws.instance_type = "t1.micro"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/xxxxx/keyname.pem"
  end
end